config/routes.rb
Rails.application.routes.draw do

  root to: "pages#index"

  get 'pages/about'
  get 'posts/index'
  get 'posts/new'
  post 'posts/create'
  get 'posts/search'
  get 'posts/search_symptom'

  get 'posts/:id' => 'posts#show'
  get 'posts/:id/edit' => 'posts#edit'
  post 'posts/:id/update' => 'posts#update'
  post 'posts/:id/delete' => 'posts#delete'

  post 'likes/:post_id/create' => 'likes#create'
  post '/likes/:post_id/destroy' => 'likes#destroy'
  get 'admin/users/:id/likes' => 'admin/users#likes'

  get 'admin/users/:id/following' => 'admin/users#following'
  get 'admin/users/:id/followers' => 'admin/users#followers'

  resources :relationships, only: [:create, :destroy]

  resources :messages, :only => [:create]

  get 'rooms/show'
  resources :rooms, :only => [:create, :show]

  resources :posts do
    resources :comments
  end

 #adimnルート
  namespace :admin do
    resources :users
  end

  get '/login',to: 'sessions#new'
  post 'login',to: 'sessions#create'
  delete '/logout',to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, {presence: true}
    validates :email, {presence: true}
    validates :password, {presence: true,uniqueness: true}

    has_many :posts,  :dependent => :destroy
    has_many :likes,  :dependent => :destroy
    has_many :comments,  :dependent => :destroy

    has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
    has_many :followings, through: :following_relationships
    has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
    has_many :followers, through: :follower_relationships


    has_many :messages,:dependent => :destroy
    has_many :entries,:dependent => :destroy

    has_secure_password


    def following?(other_user)
      following_relationships.find_by(following_id: other_user.id)
    end

    def follow!(other_user)
      following_relationships.create!(following_id: other_user.id)
    end

    def unfollow!(other_user)
      following_relationships.find_by(following_id: other_user.id).destroy
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user,{only: [:show,:update,:logout]}
  before_action :forbid_login_user,{only: [:new,:create,:login,:login_form]}

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.image ="defalut_user.jpg"
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "登録しました"
      redirect_to("/")
    else
      flash[:notice] = "登録に失敗しました"
      render("pages/index")
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    @posts = @user.posts.all
    @currentUserEntry = Entry.where(user_id: @current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    if @user.id == @current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @userRoom_id = u.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
   end


  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    @user.name = params[:name]
    @user.email = params[:email]
    @user.password = params[:password]
    @user.password_confirmation = params[:password_confirmation]
    if image = params[:image]
      @user.image = "#{@user.id}.jpg"
      File.binwrite("public/#{@user.image}",image.read)
    end

    if @user.save
      flash[:notice] = "変更しました"
      redirect_to("/users/#{@user.id}")
    else
      flash[:notice] = "変更できませんでした（入力漏れに注意してください）"
      render("users/edit")
    end
  end



  def likes
    @user = User.find_by(id: params[:id])
    @likes = Like.where(user_id: @user.id).page(params[:page]).per(3)
  end

  def following
      @user  = User.find(params[:id])
      @users = @user.followings
      render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end




private

  def user_params
    params.permit(:name, :email,:password, :password_confirmation,:image,:admin)
  end

end

app/helpers/users_helper.rb
module UsersHelper
  
end

app/views/admin/users/_follow.html.erb
<%= form_for(@current_user.following_relationships.build(following_id: @user.id)) do |f| %>
 <div><%= f.hidden_field :following_id %></div>
 <p><%= f.submit "Follow", class: "btn btn-large btn-primary follow-btn" %></p>
<% end %>

app/views/admin/users/_follow_form.html.erb
<% unless @user == @current_user %>
<div id="follow_form">
  <% if @current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
</div>
<% end %>

app/views/admin/users/_stats.html.erb
<% @user ||= @current_user %>
  <div class="stats">
  <a href="<%= "#{@user.id}/following" %>">
    <strong id="following" class="stat">
      <%= @user.followings.count %>
    </strong>
    following
  </a>
  <a href="<%= "#{@user.id}/followers" %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/admin/users/_unfollow.html.erb
<%= form_for(@current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
  <p><%= f.submit "Unfollow", class: "btn btn-large btn-default follow-btn" %></p>
<% end %>

app/views/admin/users/edit.html.erb
<div class="row">
 <div class="col-md-offset-2 col-md-8">
  <div class="center"><h1><%= @current_user.name %></h1></div>
  <div class="main-content-wrapper">
    <div class="main-content">
     <%= form_tag(admin_users_path ,{multipart: true}) do %>
      <p>画像</p>
      <div class="straight"><input name="image" type="file"></div>
      <p>ログイン名</p>
      <p2>※必須です</p2>
      <p><textarea name ="name" rows="1" cols="30"><%= @user.name %></textarea></p>
      <p>メールアドレス</p>
      <p2>※必須です</p2>
      <p><textarea name ="email" rows="1" cols="30"><%= @user.email %></textarea></p>
      <p>パスワード</p>
      <p2>※必須です</p2>
      <p><textarea name ="password" rows="1" type="password"><%= @user.password %></textarea></p>
      <p>パスワード（確認）</p>
      <p2>※必須です</p2>
      <p><textarea name ="password_confirmation" rows="1" type="password"><%= @user.password %></textarea></p>
      <p><input type="submit" value="変更"></p>
     <% end %>
   </div>
  </div>
 </div>
</div>

app/views/admin/users/likes.html.erb
<div class="row">
 <div class="col-md-offset-2 col-md-8">

  <div class="center">
      <h1>いいね！一覧</h1>
      <p>ログイン名</p>
      <p><%= @current_user.name %></p>
  </div>

  <div class="main-content">
    <% @likes.each do |like| %>

     <% post = Post.find_by(id: like.post_id) %>
      <div class="main-post-content">
       <% user = User.find_by(id: like.user_id) %>
          <div class="float"><%= image_tag "/#{like.post.user.image}", :width => '120', :height => '120' %></div>

          <div class="head-index">
            <div class="body-index">
            <div class="head-index">名前</div>
            <div class="head-index"><p><%= link_to(post.name,"/admin/users/#{post.user_id}") %></p></div>
          </div>

          <div class="body-index">
            <div class="head-index">病名</div>
            <div class="head-index"><p><%= post.sick_name %></p></div>
          </div>

          <div class="body-index">
             <div class="head-index">期間</div>
             <div class="head-index"><p><%= post.period %></p></div>
          </div>
          </div>


            <div class="body-index"><p1>初期症状</p1>
              <p><%= post.initial_symptom %></p>
            </div>
            <div class="body-index"><p1>内容</p1>
            <p><%= post.content %></p>
          </div>

          <div class="float-index">
            <% if Like.find_by(user_id: @current_user.id,post_id: post.id) %>
              <%= link_to("/likes/#{post.id}/destroy" , {method: "post"}) do %>
              <span><i class="fa fa-heart unlike-like-btn fa-2x"></i></span>
              <% end %>
            <% else %>
              <%= link_to("/likes/#{post.id}/create" , {method: "post"}) do %>
              <span><i class="fa fa-heart like-btn fa-2x"></i></span>
              <% end %>
            <% end %>
            <% likes_count = Like.where(post_id: post.id).count %>
            <%= likes_count %>
          </div>

      </div>
   　<% end %>
   <div class="center"><%= paginate @likes %></div>
  </div>

 </div>
</div>

app/views/admin/users/login_form.html.erb
<div class="row">
 <div class="col-md-offset-2 col-md-8">
    <h1>ログイン画面</h1>
  <div class="main-content-wrapper">
    <div class="main-content">
      <%= form_tag ("/admin/users/login") do  %>
        <div class="form">
          <p>名前</p>
          <input type="text" name = "name">
        </div>
      <div class="form">
        <p>パスワード</p>
        <input name = "password" type="password">
        <input type ="submit" value="ログイン">
      </div>
    <% end %>
   </div>
  </div>
 </div>
</div>

app/views/admin/users/new.html.erb
<div id="bbb" class="row">
  <div class="col-md-offset-2 col-md-8">
    <h1>ユーザー登録</h1>
    <div class="main-content">
      <%= form_tag ("/users/create") do  %>
      <div class="form">
        <p>名前</p>
        <input type="text" name = "name">
      </div>
      <div class="form">
        <p>パスワード</p>
        <input name = "password" type="password">
        <div class="form-check">
          <%= f.label :admin, class: 'form-check-label' do %>
          <%= f.check_box :admin, class: 'form-check-input' %>
          管理者権限
          <% end %>
        </div>
        <input type ="submit" value="登録">
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="row">
<div class="col-md-offset-2 col-md-8">
  <div class="center"><h1><%= @user.name %></h1></div>
  <p style="text-align:center"><%= image_tag "/#{@user.image}", :width => '120', :height => '120' %></p>


  <% if @user == @current_user %>
    <div class="editrial">
      <p><%= link_to('ユーザー編集',"/admin/users/#{@user.id}/edit") %></p>
      <p><%= link_to('いいね！一覧',"/admin/users/#{@user.id}/likes") %></p>
    </div>
  <% else %>
    <div class="center">
      <% if @isRoom == true %>
        <p class="chat-main-wrapper"><%= link_to('チャットへ',"/rooms/#{@userRoom_id}") %></p>
    </div>
    <% else %>
    <div>
      <%= form_for @room do |f| %>
        <%= fields_for @entry do |e| %>
          <%= e.hidden_field :user_id, :value=> @user.id %>
          <% end %>
        <%= f.submit(["チャットを始める"],class: 'chat-form') %>
      <% end %>
    </div>
    <% end %>
  <% end %>

  <div class="follow-user">
    <%= render 'follow_form' %>
    <%= render 'stats' %>
  </div>


  <h2><%= @user.name %> の投稿一覧</h2>
  <div class="main-content">
    <% @posts.each do |post| %>
    <div class="main-post-content">
      <div class="float"><%= image_tag "/#{post.user.image}", :width => '120', :height => '120' %></div>

     <div class="head-index">

      <div class="body-index">
       <div class="head-index">名前</div>
       <div class="head-index"><p><%= post.name %></p></div>
      </div>

     <div class="body-index">
       <div class="head-index">病名</div>
       <div class="head-index"><p><%= post.sick_name %></p></div>
     </div>

      <div class="body-index">
        <div class="head-index">期間</div>
        <div class="head-index"><p><%= post.period %></p></div>
      </div>

      </div>

      <div class="left">
        <div class="body-index"><p1>初期症状</p1>
          <p><%= post.initial_symptom %></p>
        </div>
        <div class="body-index"><p1>内容</p1>
          <p><%= post.content %></p>
        </div>
      </div>

      <% #if @user == @current_user %>
      <div class="detail"><%= link_to("詳細","/posts/#{post.id}",:style=>"color:black;" ) %></div>
      <% #end %>
      </div>

    <% end %>
  </div>

　</div>
</div>

app/views/admin/users/show_follow.html.erb
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="main-content">
      <div class="center"><h1>フォロー</h1></div>
      <% @user.followings.each do |user| %>
      <table>
        <tr>
          <td><%= image_tag "/#{user.image}", :width => '100', :height => '100' %></td>
          <td><%= user.name %></td>
          <td><%= link_to '詳細', "/admin/users/#{user.id}" %></td>
        </tr>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/show_follower.html.erb
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="main-content">
      <div class="center"><h1>フォロワー</h1></div>
      <% @user.followers.each do |user| %>
      <table>
        <tr>
          <td><%= image_tag "/#{user.image}", :width => '100', :height => '100' %></td>
          <td><%= user.name %></td>
          <td><%= link_to '詳細', "/admin/users/#{user.id}" %></td>
        </tr>
      </table>
      <% end %>
    </div>
  </div>
</div>